///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PrimeServiceRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ea9c3029-ae79-466b-af9c-fd3cd3c97ef8")]
    public partial class PrimeServiceRepository : RepoGenBaseFolder
    {
        static PrimeServiceRepository instance = new PrimeServiceRepository();
        PrimeServiceRepositoryFolders.Form1AppFolder _form1;
        PrimeServiceRepositoryFolders.PrimeServiceWinFormAppFolder _primeservicewinform;
        PrimeServiceRepositoryFolders.СообщенияAppFolder _сообщения;
        PrimeServiceRepositoryFolders.ПереключениеЗадачAppFolder _переключениезадач;

        /// <summary>
        /// Gets the singleton class instance representing the PrimeServiceRepository element repository.
        /// </summary>
        [RepositoryFolder("ea9c3029-ae79-466b-af9c-fd3cd3c97ef8")]
        public static PrimeServiceRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PrimeServiceRepository() 
            : base("PrimeServiceRepository", "/", null, 0, false, "ea9c3029-ae79-466b-af9c-fd3cd3c97ef8", ".\\RepositoryImages\\PrimeServiceRepositoryea9c3029.rximgres")
        {
            _form1 = new PrimeServiceRepositoryFolders.Form1AppFolder(this);
            _primeservicewinform = new PrimeServiceRepositoryFolders.PrimeServiceWinFormAppFolder(this);
            _сообщения = new PrimeServiceRepositoryFolders.СообщенияAppFolder(this);
            _переключениезадач = new PrimeServiceRepositoryFolders.ПереключениеЗадачAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ea9c3029-ae79-466b-af9c-fd3cd3c97ef8")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("671b2cad-895a-4571-b311-3120d3ede88c")]
        public virtual PrimeServiceRepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The PrimeServiceWinForm folder.
        /// </summary>
        [RepositoryFolder("9f41cf92-932a-4f82-9b1a-b8e641f06fde")]
        public virtual PrimeServiceRepositoryFolders.PrimeServiceWinFormAppFolder PrimeServiceWinForm
        {
            get { return _primeservicewinform; }
        }

        /// <summary>
        /// The Сообщения folder.
        /// </summary>
        [RepositoryFolder("ea05007e-1f1a-4ebe-8ac6-e96b766a4635")]
        public virtual PrimeServiceRepositoryFolders.СообщенияAppFolder Сообщения
        {
            get { return _сообщения; }
        }

        /// <summary>
        /// The ПереключениеЗадач folder.
        /// </summary>
        [RepositoryFolder("edd6ee58-8c38-4275-aab6-8764298f7d97")]
        public virtual PrimeServiceRepositoryFolders.ПереключениеЗадачAppFolder ПереключениеЗадач
        {
            get { return _переключениезадач; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PrimeServiceRepositoryFolders
    {
        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("671b2cad-895a-4571-b311-3120d3ede88c")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _button1Info;
            RepoItemInfo _label2Info;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 30000, null, true, "671b2cad-895a-4571-b311-3120d3ede88c", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "e73bf67a-7d9e-4177-b318-a1cd766658d9");
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", 30000, null, "9a167b77-d2d3-4e6a-b3f4-ebf1cb23b495");
                _label2Info = new RepoItemInfo(this, "Label2", "text[@controlname='label2']", 30000, null, "e91f7eb7-5d51-49b1-b8cc-0699cb4bfdbb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("671b2cad-895a-4571-b311-3120d3ede88c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("671b2cad-895a-4571-b311-3120d3ede88c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("e73bf67a-7d9e-4177-b318-a1cd766658d9")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("e73bf67a-7d9e-4177-b318-a1cd766658d9")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("9a167b77-d2d3-4e6a-b3f4-ebf1cb23b495")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("9a167b77-d2d3-4e6a-b3f4-ebf1cb23b495")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Label2 item.
            /// </summary>
            [RepositoryItem("e91f7eb7-5d51-49b1-b8cc-0699cb4bfdbb")]
            public virtual Ranorex.Text Label2
            {
                get
                {
                    return _label2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Label2 item info.
            /// </summary>
            [RepositoryItemInfo("e91f7eb7-5d51-49b1-b8cc-0699cb4bfdbb")]
            public virtual RepoItemInfo Label2Info
            {
                get
                {
                    return _label2Info;
                }
            }
        }

        /// <summary>
        /// The PrimeServiceWinFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f41cf92-932a-4f82-9b1a-b8e641f06fde")]
        public partial class PrimeServiceWinFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;
            RepoItemInfo _text65535Info;
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new PrimeServiceWinForm  folder.
            /// </summary>
            public PrimeServiceWinFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PrimeServiceWinForm", "/form[@title='']", parentFolder, 30000, null, true, "9f41cf92-932a-4f82-9b1a-b8e641f06fde", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "button[@text='ОК']", 30000, null, "53b8a1fd-bf1c-4709-98a1-320017bad1ad");
                _text65535Info = new RepoItemInfo(this, "Text65535", "text[@controlid='65535']", 30000, null, "1ff876dd-2028-4de7-a03e-1ea12f361c2a");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/button[@accessiblename='Закрыть']", 30000, null, "e7f5d125-5a64-4f77-aa54-91598cd281ae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f41cf92-932a-4f82-9b1a-b8e641f06fde")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f41cf92-932a-4f82-9b1a-b8e641f06fde")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("53b8a1fd-bf1c-4709-98a1-320017bad1ad")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("53b8a1fd-bf1c-4709-98a1-320017bad1ad")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }

            /// <summary>
            /// The Text65535 item.
            /// </summary>
            [RepositoryItem("1ff876dd-2028-4de7-a03e-1ea12f361c2a")]
            public virtual Ranorex.Text Text65535
            {
                get
                {
                    return _text65535Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text65535 item info.
            /// </summary>
            [RepositoryItemInfo("1ff876dd-2028-4de7-a03e-1ea12f361c2a")]
            public virtual RepoItemInfo Text65535Info
            {
                get
                {
                    return _text65535Info;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("e7f5d125-5a64-4f77-aa54-91598cd281ae")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("e7f5d125-5a64-4f77-aa54-91598cd281ae")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }
        }

        /// <summary>
        /// The СообщенияAppFolder folder.
        /// </summary>
        [RepositoryFolder("ea05007e-1f1a-4ebe-8ac6-e96b766a4635")]
        public partial class СообщенияAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Сообщения  folder.
            /// </summary>
            public СообщенияAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Сообщения", "/dom[@domain='vk.com']", parentFolder, 30000, null, false, "ea05007e-1f1a-4ebe-8ac6-e96b766a4635", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ea05007e-1f1a-4ebe-8ac6-e96b766a4635")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ea05007e-1f1a-4ebe-8ac6-e96b766a4635")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ПереключениеЗадачAppFolder folder.
        /// </summary>
        [RepositoryFolder("edd6ee58-8c38-4275-aab6-8764298f7d97")]
        public partial class ПереключениеЗадачAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ПереключениеЗадач  folder.
            /// </summary>
            public ПереключениеЗадачAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ПереключениеЗадач", "/form[@title='Переключение задач']", parentFolder, 30000, null, true, "edd6ee58-8c38-4275-aab6-8764298f7d97", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("edd6ee58-8c38-4275-aab6-8764298f7d97")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("edd6ee58-8c38-4275-aab6-8764298f7d97")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
