///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("cda018b5-6a89-4a5f-9c0d-0257be30c58f", ModuleType.Recording, 1)]
    public partial class Recording2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PrimeServiceRepository repository.
        /// </summary>
        public static PrimeServiceRepository repo = PrimeServiceRepository.Instance;

        static Recording2 instance = new Recording2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording2()
        {
            FalseValue = "";
            FalseResult = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _FalseValue;

        /// <summary>
        /// Gets or sets the value of variable FalseValue.
        /// </summary>
        [TestVariable("5c610b7e-5c0d-4003-be3d-506455f66098")]
        public string FalseValue
        {
            get { return _FalseValue; }
            set { _FalseValue = value; }
        }

        string _FalseResult;

        /// <summary>
        /// Gets or sets the value of variable FalseResult.
        /// </summary>
        [TestVariable("e2f9cb6a-4afb-48c7-a5ca-d8ff47e75904")]
        public string FalseResult
        {
            get { return _FalseResult; }
            set { _FalseResult = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form1.Text' at 200;10.", repo.Form1.TextInfo, new RecordItemIndex(0));
            repo.Form1.Text.Click("200;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$FalseValue' with focus on 'Form1.Text'.", repo.Form1.TextInfo, new RecordItemIndex(1));
            repo.Form1.Text.PressKeys(FalseValue);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$FalseResult) on item 'PrimeServiceWinForm.Text65535'.", repo.PrimeServiceWinForm.Text65535Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.PrimeServiceWinForm.Text65535Info, "Text", FalseResult);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'PrimeServiceWinForm' at 275;128.", repo.PrimeServiceWinForm.SelfInfo, new RecordItemIndex(3));
            repo.PrimeServiceWinForm.Self.Click("275;128");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
